version: "3.7"
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./postgresdb:/var/lib/postgresql:rw
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - 50002:5432

  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
    #  - "3000:3000"
      - "5001:5000"
    depends_on:
      - postgres
    #environment:
    #  - "TERM=xterm"
    restart: on-failure