version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: pg_container
    restart: always
    volumes:
      - postgresdb:/var/lib/postgresql
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - 50002:5432

  app:
    container_name: app
    image: app
    build:
      context: .
      dockerfile: "Dockerfile"
    links:
      - postgres
    environment:
      - PGPASSWORD=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGHOST=database
      - PGPORT=5432
    volumes:
      - $PWD/application/:/src/application
    ports:
      - "8889:8888"

    depends_on:
      - postgres
    restart: on-failure

volumes:
  postgresdb: {}